### ISSUE TITLE
any instructions on how to use this docker

### ISSUE THREAD

**Issue by SydOps** [klokoy/pdf2htmlEX_docker#2]
Could you please give some instructions on how to use this docker.

If possible, could you please rebuild the Dockerfile with Archlinux or Alpine linux and reduce the image size. 

Currently, the size is 1GB, too big.

**Comment by SydOps** [comment]
Ok, I know how to use it now. 
```
docker run -ti -v ~/pdf:/pdf klokoy/pdf2htmlex
root@ef12bd470e34:/# pdf2htmlex --zoom 1.3 pdf/test.pdf
```

**Comment by klokoy** [comment]
I have been thinking about reducing the size of this image.  Hopefully I might get arond to do that quite soon.

**Comment by SydOps** [comment]
Nice, wait for that.

**Comment by klokoy** [comment]
Created new issue for image size
